### ISSUE TITLE
Adding support for Paraswap & 0x aggregator

### ISSUE THREAD

**Issue by KaymasJain** [Instadapp/dsa-connectors#109]
Add connectors for [Paraswap](https://paraswap.io/) & [0x](https://0x.org/).

Paraswap & 0x are the DEX aggregators just like 1inch. On our UI we'll start to route our trade by comparing prices from all these aggregators.

Support on:-
- Mainnet
- Polygon
- Avalanche
- Arbitrum

For reference - we already have the support Paraswap connector on [Polygon](https://github.com/Instadapp/dsa-connectors/tree/main/contracts/polygon/connectors/paraswap).

**Comment by pradyuman-verma** [comment]
completed in #127 #144 #146

**Comment by pradyuman-verma** [comment]
0x added on - polygon, avalanche, mainnet
paraswap on - polygon, avalanche

Both of these are not on arbitrum!
