### ISSUE TITLE
Create a simple Uniswap v3 swap connector on Arbitrum

### ISSUE THREAD

**Issue by KaymasJain** [Instadapp/dsa-connectors#113]
Just one function as `sell()` with params as
```
        address tokenIn;
        address tokenOut;
        uint24 fee;
        address recipient;
        uint256 deadline;
        uint256 amountIn;
        uint256 amountOutMinimum;
        uint160 sqrtPriceLimitX96;
```
One thing that we need to figure out is how to calculate `sqrtPriceLimitX96`. I'll also ask this to some other devs :)

- Convert the Param into this struct inside the function `ExactInputSingleParams`. Search struct [here](https://docs.uniswap.org/protocol/reference/periphery/interfaces/ISwapRouter#exactinputsingleparams)
- Then call this function `exactInputSingle` for swap [here](https://docs.uniswap.org/protocol/reference/periphery/interfaces/ISwapRouter#exactinputsingle) (make sure to approve token before calling this function).
- Address for the swap [here](https://github.com/Uniswap/v3-periphery/blob/main/deploys.md). I think it should be a swap router.

Update: To calculate `sqrtPriceLimitX96` this should help - https://docs.uniswap.org/protocol/reference/core/libraries/SqrtPriceMath

**Comment by KaymasJain** [comment]
Also, we can remove these params:-
- `deadline` keep it hardcoded as `block.timestamp + 1`.
- `recipient` as `address(this)`
- `sqrtPriceLimitX96` calculate it through that library on the smart contract itself. Let me know if it makes the code complex.

**Comment by pradyuman-verma** [comment]
closing it now.
