### ISSUE TITLE
Basic A connector update

### ISSUE THREAD

**Issue by KaymasJain** [Instadapp/dsa-connectors#215]
Add transferFrom from any address in the basic connector. So will need to add a new deposit function with extra param as `address from_` - https://github.com/Instadapp/dsa-connectors/blob/main/contracts/mainnet/connectors/basic/main.sol#L27

**Comment by thrilok209** [comment]
Function name could be `depositFrom`.

**Comment by KaymasJain** [comment]
And params as `address tkn, uint amt, address from, uint getId, uint setId`

**Comment by shriyatyagii** [comment]
Hey, this update was done long back - https://github.com/Instadapp/dsa-connectors/blob/main/contracts/mainnet/connectors/basic/main.sol#L57

Closing it.
