### ISSUE TITLE
Interactive deployment script for connectors

### ISSUE THREAD

**Issue by thrilok209** [Instadapp/dsa-connectors#78]
We need to create a script for deploying connector,  a command like `npm run deploy`. it should ask which connector to deploy, chain, gasPrices.

**Comment by Sowmayjain** [comment]
@thrilok209 I think, to reduce the error mistakes, we should have a `dsa-config.json` file which have the list of connectors, chain, gasPrices, etc and when we run `npm run deploy`, it will read that data and execute stuff accordingly.

**Comment by thrilok209** [comment]
@Sowmayjain For that, we need to edit the file, it will show that the file is changed, and need to commit. If it's CLI, then it will show us the options for connector and we can simply set gasPrice and chain according. 

Also, we can have a backup command which will take command-line argument. Eg: `npm run deploy --connector=compound --network=mainnet --gasprice=89`

**Comment by cryptoDev222** [comment]
I think network param will be from the hardhat config file.

**Comment by thrilok209** [comment]
> I think network param will be from the hardhat config file.

I think we can do it in latest version of hardhat.

**Comment by Sowmayjain** [comment]
Okay, take your call. Initial, I thought it's for deploying connectors on a new chain altogether. After giving a closer look, got to know that it's for individual deployment. Your take is correct.
